export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' }
];

export const COUNTRY_CODES = [
  { value: '+1', label: 'United States (+1)', country: 'US' },
  { value: '+44', label: 'United Kingdom (+44)', country: 'GB' },
  { value: '+91', label: 'India (+91)', country: 'IN' },
  { value: '+86', label: 'China (+86)', country: 'CN' },
  { value: '+81', label: 'Japan (+81)', country: 'JP' },
  { value: '+49', label: 'Germany (+49)', country: 'DE' },
  { value: '+33', label: 'France (+33)', country: 'FR' },
  { value: '+39', label: 'Italy (+39)', country: 'IT' },
  { value: '+34', label: 'Spain (+34)', country: 'ES' },
  { value: '+61', label: 'Australia (+61)', country: 'AU' },
  { value: '+55', label: 'Brazil (+55)', country: 'BR' },
  { value: '+7', label: 'Russia (+7)', country: 'RU' },
  { value: '+82', label: 'South Korea (+82)', country: 'KR' },
  { value: '+52', label: 'Mexico (+52)', country: 'MX' },
  { value: '+27', label: 'South Africa (+27)', country: 'ZA' },
  { value: '+971', label: 'UAE (+971)', country: 'AE' },
  { value: '+966', label: 'Saudi Arabia (+966)', country: 'SA' },
  { value: '+65', label: 'Singapore (+65)', country: 'SG' },
  { value: '+41', label: 'Switzerland (+41)', country: 'CH' },
  { value: '+31', label: 'Netherlands (+31)', country: 'NL' },
  { value: '+46', label: 'Sweden (+46)', country: 'SE' },
  { value: '+47', label: 'Norway (+47)', country: 'NO' },
  { value: '+45', label: 'Denmark (+45)', country: 'DK' },
  { value: '+358', label: 'Finland (+358)', country: 'FI' },
  { value: '+32', label: 'Belgium (+32)', country: 'BE' },
  { value: '+43', label: 'Austria (+43)', country: 'AT' },
  { value: '+48', label: 'Poland (+48)', country: 'PL' },
  { value: '+420', label: 'Czech Republic (+420)', country: 'CZ' },
  { value: '+351', label: 'Portugal (+351)', country: 'PT' },
  { value: '+30', label: 'Greece (+30)', country: 'GR' },
  { value: '+90', label: 'Turkey (+90)', country: 'TR' },
  { value: '+20', label: 'Egypt (+20)', country: 'EG' },
  { value: '+972', label: 'Israel (+972)', country: 'IL' },
  { value: '+852', label: 'Hong Kong (+852)', country: 'HK' },
  { value: '+886', label: 'Taiwan (+886)', country: 'TW' },
  { value: '+66', label: 'Thailand (+66)', country: 'TH' },
  { value: '+60', label: 'Malaysia (+60)', country: 'MY' },
  { value: '+62', label: 'Indonesia (+62)', country: 'ID' },
  { value: '+63', label: 'Philippines (+63)', country: 'PH' },
  { value: '+84', label: 'Vietnam (+84)', country: 'VN' },
  { value: '+64', label: 'New Zealand (+64)', country: 'NZ' }
];

export const COUNTRIES = [
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'DE', label: 'Germany' },
  { value: 'FR', label: 'France' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'BE', label: 'Belgium' },
  { value: 'AT', label: 'Austria' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'DK', label: 'Denmark' },
  { value: 'FI', label: 'Finland' },
  { value: 'IE', label: 'Ireland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'GR', label: 'Greece' },
  { value: 'PL', label: 'Poland' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'HU', label: 'Hungary' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'HR', label: 'Croatia' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'RO', label: 'Romania' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LV', label: 'Latvia' },
  { value: 'EE', label: 'Estonia' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MT', label: 'Malta' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'AU', label: 'Australia' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'JP', label: 'Japan' },
  { value: 'KR', label: 'South Korea' },
  { value: 'CN', label: 'China' },
  { value: 'IN', label: 'India' },
  { value: 'SG', label: 'Singapore' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TH', label: 'Thailand' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'PH', label: 'Philippines' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'BR', label: 'Brazil' },
  { value: 'MX', label: 'Mexico' },
  { value: 'AR', label: 'Argentina' },
  { value: 'CL', label: 'Chile' },
  { value: 'CO', label: 'Colombia' },
  { value: 'PE', label: 'Peru' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'EG', label: 'Egypt' },
  { value: 'IL', label: 'Israel' },
  { value: 'AE', label: 'United Arab Emirates' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'TR', label: 'Turkey' },
  { value: 'RU', label: 'Russia' }
];